services:
  api:
    build: .
    container_name: delivery-api
    restart: always
    image: python:3.12-slim
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Amir2002_@db:5432/delivery_db
      - JWT_SECRET_KEY=iu3tg6438gr8cx71987ruy1498ruy2498ruy2498ruy
      - ENVIRONMENT=production
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://72.61.116.31:5173,http://72.61.116.31:6000}
      - UPLOAD_DIR=/app/uploads
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Amir2002_
      POSTGRES_DB: delivery_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  uploads_data:
